// react/src/components/EditNoteModal.tsx
import { useState } from "react";
import { useAuth } from "@clerk/clerk-react";
import {
  Modal,
  Button,
  TextInput,
  Textarea,
  Stack,
  Group,
  Alert,
  Radio,
  RadioGroup,
  Flex,
} from "@mantine/core";
import { useForm } from "@mantine/form";

interface Note {
  id: string;
  title: string;
  content: string;
  isPublic: string;
  userId: string | null;
}

interface EditNoteModalProps {
  note: Note | null;
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  isAdmin?: boolean;
}

const EditNoteModal = ({
  note,
  isOpen,
  onClose,
  onSuccess,
  isAdmin = false,
}: EditNoteModalProps) => {
  const { getToken } = useAuth();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const form = useForm({
    initialValues: {
      title: note?.title || "",
      content: note?.content || "",
      isPublic: note?.isPublic === "true" || false,
    },
    validate: {
      title: (value) =>
        value.trim().length > 0 ? null : "Title cannot be empty",
      content: (value) =>
        value.trim().length > 0 ? null : "Content cannot be empty",
    },
  });

  // Update form values when note changes
  if (note && form.values.title !== note.title) {
    form.setValues({
      title: note.title,
      content: note.content,
      isPublic: note.isPublic === "true",
    });
  }

  const handleSubmit = async (values: {
    title: string;
    content: string;
    isPublic: boolean;
  }) => {
    if (!note || !note.id) {
      setError("Cannot edit: note data is missing");
      return;
    }

    try {
      setIsSubmitting(true);
      setError(null);

      let response;
      const token = isAdmin
        ? localStorage.getItem("adminApiKey") || ""
        : await getToken();

      if (isAdmin) {
        // Admin update path
        response = await fetch(`/api/notes/${note.id}/admin`, {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
            "X-API-Key": token as string,
          },
          body: JSON.stringify(values),
        });
      } else if (note.isPublic === "true" && !note.userId) {
        // Public anonymous notes
        response = await fetch(`/api/public-notes/${note.id}`, {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(values),
        });
      } else {
        // User's own notes
        response = await fetch(`/api/notes/${note.id}`, {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify(values),
        });
      }

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || "Failed to update note");
      }

      onSuccess();
      onClose();
    } catch (err) {
      console.error("Error updating note:", err);
      setError(err instanceof Error ? err.message : "Failed to update note");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Modal
      opened={isOpen}
      onClose={onClose}
      title="Edit Note"
      size="lg"
      centered
      overlayProps={{
        backgroundOpacity: 0.55,
        blur: 3,
      }}
      styles={{
        root: {
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        },
        content: {
          width: "100%",
          maxWidth: "600px",
          margin: "0 auto",
        },
      }}
    >
      {error && (
        <Alert color="red" title="Error" mb="md" onClose={() => setError(null)}>
          {error}
        </Alert>
      )}

      <form onSubmit={form.onSubmit(handleSubmit)}>
        <Stack>
          <TextInput
            label="Title"
            placeholder="Note title"
            {...form.getInputProps("title")}
            disabled={isSubmitting}
            required
          />

          <Textarea
            label="Content"
            placeholder="Note content"
            minRows={4}
            {...form.getInputProps("content")}
            disabled={isSubmitting}
            required
          />

          {(isAdmin || note?.userId) && (
            <RadioGroup
              value={form.values.isPublic ? "true" : "false"}
              onChange={(value) =>
                form.setFieldValue("isPublic", value === "true")
              }
              label="Note visibility"
              description="Choose who can see this note"
            >
              <Flex gap="md" mt="xs">
                <Radio
                  value="false"
                  label="Private - Only you can see this note"
                />
                <Radio value="true" label="Public - Anyone can see this note" />
              </Flex>
            </RadioGroup>
          )}

          <Group justify="space-between" mt="md">
            <Button variant="subtle" onClick={onClose} disabled={isSubmitting}>
              Cancel
            </Button>
            <Button type="submit" loading={isSubmitting}>
              Save Changes
            </Button>
          </Group>
        </Stack>
      </form>
    </Modal>
  );
};

export default EditNoteModal;

// vue/src/components/EditNoteModal.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useAuth } from '@clerk/vue';
import type { Note } from '../types/note';
import Dialog from 'primevue/dialog';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import Textarea from 'primevue/textarea';
import Checkbox from 'primevue/checkbox';
import Message from 'primevue/message';

const props = defineProps<{
  note: Note;
  isAdmin?: boolean;
  adminApiKey?: string | null;
}>();
const emit = defineEmits<{ updated: []; close: [] }>();

const { getToken } = useAuth();
const title = ref(props.note.title ?? '');
const content = ref(props.note.content ?? '');
const isPublic = ref(props.note.isPublic === 'true');
const submitting = ref(false);
const error = ref<string | null>(null);
const visible = ref(true);

async function handleSubmit() {
  if (!content.value.trim()) { error.value = 'Content cannot be empty'; return; }
  submitting.value = true;
  error.value = null;
  try {
    const note = props.note;
    const isAnonymousPublic = note.isPublic === 'true' && (note.userId == null || note.userId === '');

    let res: Response;
    if (props.isAdmin && props.adminApiKey) {
      res = await fetch(`/api/notes/${note.id}/admin`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'X-API-Key': props.adminApiKey,
        },
        body: JSON.stringify({ title: title.value, content: content.value, isPublic: isPublic.value }),
      });
    } else if (isAnonymousPublic) {
      res = await fetch(`/api/public-notes/${note.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: title.value.trim() || 'Public Note',
          content: content.value,
          isPublic: isPublic.value,
        }),
      });
    } else {
      const token = await getToken.value();
      res = await fetch(`/api/notes/${note.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ title: title.value, content: content.value, isPublic: isPublic.value }),
      });
    }
    if (!res.ok) {
      const data: { error?: string } = await res.json().catch(() => ({}));
      throw new Error(data.error || 'Failed to update note');
    }
    emit('updated');
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to update note';
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <Dialog
    v-model:visible="visible"
    header="Edit Note"
    :modal="true"
    :style="{ width: '480px' }"
    @hide="emit('close')"
  >
    <form @submit.prevent="handleSubmit" class="note-form">
      <div class="field">
        <label class="field-label">Title</label>
        <InputText v-model="title" placeholder="Note title" class="w-full" />
      </div>
      <div class="field">
        <label class="field-label">Content</label>
        <Textarea v-model="content" rows="4" placeholder="Note content" class="w-full" required />
      </div>
      <div class="field field--checkbox">
        <Checkbox v-model="isPublic" inputId="edit-public" :binary="true" />
        <label for="edit-public" class="field-label">Make public</label>
      </div>
      <Message v-if="error" severity="error" :closable="false">{{ error }}</Message>
      <div class="dialog-footer">
        <Button type="button" label="Cancel" severity="secondary" text @click="emit('close')" />
        <Button type="submit" label="Save Changes" :loading="submitting" />
      </div>
    </form>
  </Dialog>
</template>

<style scoped>
.note-form { display: flex; flex-direction: column; gap: 1rem; }
.field { display: flex; flex-direction: column; gap: 0.35rem; }
.field--checkbox { flex-direction: row; align-items: center; gap: 0.5rem; }
.field-label { font-size: 0.875rem; font-weight: 500; color: #374151; }
.w-full { width: 100%; }
.dialog-footer { display: flex; justify-content: flex-end; gap: 0.5rem; margin-top: 0.5rem; }
</style>
