// react/src/components/CodeExpander.tsx
import {useState, useEffect, useRef} from 'react';

interface CodeExpanderProps {
  code: string;
  id: string;
  label?: string;
}

declare global {
  interface Window {
    Prism?: {highlightAllUnder: (el: Element) => void};
  }
}

export function CodeExpander({code, id, label = 'React code'}: CodeExpanderProps) {
  const [open, setOpen] = useState(false);
  const panelRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (open && panelRef.current && window.Prism) {
      window.Prism.highlightAllUnder(panelRef.current);
    }
  }, [open]);

  return (
    <div style={{borderTop: '1px solid #e5e7eb', marginTop: '1rem'}}>
      <button
        type='button'
        onClick={() => setOpen((v) => !v)}
        aria-controls={`${id}-panel`}
        aria-expanded={open}
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '0.375rem',
          width: '100%',
          padding: '0.5rem 0.75rem',
          background: 'none',
          border: 'none',
          cursor: 'pointer',
          fontSize: '0.875rem',
          color: '#6b7280',
          textAlign: 'left',
          borderRadius: '0.375rem',
          transition: 'background 0.15s, color 0.15s',
        }}
        onMouseEnter={(e) => {
          (e.currentTarget as HTMLButtonElement).style.background = '#f9fafb';
          (e.currentTarget as HTMLButtonElement).style.color = '#374151';
        }}
        onMouseLeave={(e) => {
          (e.currentTarget as HTMLButtonElement).style.background = 'none';
          (e.currentTarget as HTMLButtonElement).style.color = '#6b7280';
        }}
      >
        <span style={{fontFamily: 'monospace', color: '#9ca3af'}}>&lt;/&gt;</span>
        {label}
        <span
          style={{
            marginLeft: '0.25rem',
            display: 'inline-block',
            transition: 'transform 0.2s',
            transform: open ? 'rotate(180deg)' : 'none',
          }}
        >
          ▼
        </span>
      </button>
      {open && (
        <div id={`${id}-panel`} ref={panelRef}>
          <pre className='language-javascript' style={{margin: 0, borderRadius: '0.5rem', fontSize: '0.75rem'}}>
            <code className='language-javascript'>{code}</code>
          </pre>
        </div>
      )}
    </div>
  );
}

// svelte/src/lib/components/CodeExpander.svelte
<script lang="ts">
  import { tick } from 'svelte';

  export let code: string;
  export let id: string;
  export let label: string = 'Svelte code';

  let open = false;
  let panelEl: HTMLDivElement | undefined;

  async function toggle() {
    open = !open;
    if (open) {
      await tick();
      if (panelEl && (window as any).Prism) {
        (window as any).Prism.highlightAllUnder(panelEl);
      }
    }
  }
</script>

<div class="code-expander">
  <button
    type="button"
    class="code-toggle"
    on:click={toggle}
    aria-controls="{id}-panel"
    aria-expanded={open}
  >
    <span class="code-icon">&lt;/&gt;</span>
    {label}
    <span class="chevron" class:rotated={open}>▼</span>
  </button>
  {#if open}
    <div id="{id}-panel" bind:this={panelEl}>
      <pre class="language-javascript" style="margin:0;border-radius:0.5rem;font-size:0.75rem"><code class="language-javascript">{code}</code></pre>
    </div>
  {/if}
</div>

<style>
  .code-expander {
    border-top: 1px solid #e5e7eb;
    margin-top: 1rem;
  }
  .code-toggle {
    display: flex;
    align-items: center;
    gap: 0.375rem;
    width: 100%;
    padding: 0.5rem 0.75rem;
    background: none;
    border: none;
    cursor: pointer;
    font-size: 0.875rem;
    color: #6b7280;
    text-align: left;
    border-radius: 0.375rem;
    transition: background 0.15s, color 0.15s;
  }
  .code-toggle:hover { background: #f9fafb; color: #374151; }
  .code-icon { font-family: monospace; color: #9ca3af; }
  .chevron {
    margin-left: 0.25rem;
    display: inline-block;
    transition: transform 0.2s;
  }
  .chevron.rotated { transform: rotate(180deg); }
</style>
