// vue/src/components/AdminNotesTable.vue
<script setup lang="ts">
import type { Note } from '../types/note';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import Button from 'primevue/button';
import Tag from 'primevue/tag';
import Message from 'primevue/message';
import { ref } from 'vue';

const props = defineProps<{
  notes: Note[];
  loading: boolean;
  error: string | null;
  adminApiKey: string | null;
}>();

const emit = defineEmits<{ refetch: [] }>();
const deleteError = ref<string | null>(null);
const regexInput = ref('');
const deleteByRegexLoading = ref(false);

async function handleDeleteByRegex() {
  if (!props.adminApiKey || !regexInput.value.trim()) return;
  deleteError.value = null;
  deleteByRegexLoading.value = true;
  try {
    const res = await fetch('/api/notes/admin/delete-by-regex', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-API-Key': props.adminApiKey,
      },
      body: JSON.stringify({ contentRegex: regexInput.value.trim() }),
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error((err as { error?: string }).error || `Failed: ${res.status}`);
    }
    regexInput.value = '';
    emit('refetch');
  } catch (err) {
    deleteError.value = err instanceof Error ? err.message : 'Failed to delete by regex';
  } finally {
    deleteByRegexLoading.value = false;
  }
}

function formatDate(d: string | null): string {
  if (!d) return 'N/A';
  try {
    const date = new Date(d);
    return (
      date.toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' }) +
      ', ' +
      date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    );
  } catch { return 'Invalid Date'; }
}

function getUserName(note: Note): string {
  if (note.user?.firstName) return `${note.user.firstName} ${note.user.lastName ?? ''}`.trim();
  if (note.user?.email) return note.user.email;
  if (note.userId) return `User #${note.userId}`;
  return 'Anonymous';
}

function preview(content: string): string {
  return content.length > 50 ? content.slice(0, 50) + '…' : content;
}

async function handleDelete(id: string) {
  if (!props.adminApiKey) return;
  if (!window.confirm('Are you sure you want to delete this note?')) return;
  deleteError.value = null;
  try {
    const res = await fetch(`/api/notes/${id}/admin`, {
      method: 'DELETE',
      headers: { 'X-API-Key': props.adminApiKey },
    });
    if (!res.ok) throw new Error(`Failed to delete note: ${res.status}`);
    emit('refetch');
  } catch (err) {
    deleteError.value = err instanceof Error ? err.message : 'Failed to delete note';
  }
}
</script>

<template>
  <div class="admin-section">
    <div class="section-header">
      <h2 class="section-title">All Notes (Admin View)</h2>
      <p class="section-subtitle">View and manage all notes in the system</p>
    </div>

    <Message v-if="deleteError" severity="error" :closable="false" style="margin-bottom: 1rem">
      {{ deleteError }}
    </Message>
    <Message v-if="error" severity="error" :closable="false" style="margin-bottom: 1rem">
      {{ error }}
    </Message>

    <div class="delete-by-regex-row">
      <input
        v-model="regexInput"
        type="text"
        placeholder="e.g. e2e- or ^test"
        class="regex-input"
      />
      <button
        type="button"
        class="btn-delete-matching"
        :disabled="!regexInput.trim() || !adminApiKey || deleteByRegexLoading"
        @click="handleDeleteByRegex"
      >
        {{ deleteByRegexLoading ? 'Deleting…' : 'Delete matching notes' }}
      </button>
    </div>
    <p class="regex-hint">Delete notes whose content or title matches the regex</p>

    <DataTable
      :value="notes"
      :loading="loading"
      striped-rows
      size="small"
      :paginator="notes.length > 10"
      :rows="10"
      empty-message="No notes found in the system."
      style="font-size: 0.875rem"
    >
      <Column field="title" header="Title">
        <template #body="{ data }">
          <span style="font-weight: 500">{{ data.title || 'Untitled' }}</span>
        </template>
      </Column>
      <Column header="Content Preview">
        <template #body="{ data }">{{ preview(data.content) }}</template>
      </Column>
      <Column header="Status" style="width: 100px">
        <template #body="{ data }">
          <Tag
            :value="data.isPublic === 'true' ? 'Public' : 'Private'"
            :severity="data.isPublic === 'true' ? 'success' : 'secondary'"
            rounded
          />
        </template>
      </Column>
      <Column header="Author">
        <template #body="{ data }">{{ getUserName(data) }}</template>
      </Column>
      <Column header="Created" style="width: 160px">
        <template #body="{ data }">{{ formatDate(data.createdAt) }}</template>
      </Column>
      <Column header="Updated" style="width: 160px">
        <template #body="{ data }">{{ formatDate(data.updatedAt) }}</template>
      </Column>
      <Column header="Actions" style="width: 80px">
        <template #body="{ data }">
          <Button
            icon="pi pi-trash"
            size="small"
            text
            severity="danger"
            @click="handleDelete(data.id)"
          />
        </template>
      </Column>
    </DataTable>
  </div>
</template>

<style scoped>
.admin-section {
  background: #fff;
  border-radius: 8px;
  border: 1px solid #e5e7eb;
  box-shadow: 0 1px 3px rgba(0,0,0,.06);
  padding: 1.5rem;
}

.section-header { margin-bottom: 1.25rem; }

.section-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: #1f2937;
  margin: 0 0 0.25rem 0;
}

.section-subtitle {
  font-size: 0.875rem;
  color: #6b7280;
  margin: 0;
}

.delete-by-regex-row {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.25rem;
}
.regex-input {
  flex: 1;
  min-width: 200px;
  padding: 0.5rem 0.75rem;
  border: 1px solid #e5e7eb;
  border-radius: 0.375rem;
  font-size: 0.875rem;
}
.btn-delete-matching {
  padding: 0.5rem 1rem;
  font-size: 0.875rem;
  font-weight: 500;
  color: #b91c1c;
  background: #fef2f2;
  border: 1px solid #fecaca;
  border-radius: 0.375rem;
  cursor: pointer;
}
.btn-delete-matching:hover:not(:disabled) {
  background: #fee2e2;
}
.btn-delete-matching:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
.regex-hint {
  font-size: 0.75rem;
  color: #6b7280;
  margin: 0 0 1rem 0;
}
</style>

// react/src/components/AdminNotesTable.tsx
import {useState} from 'react';
import {Text, Paper, Alert, TextInput, Button, Group} from '@mantine/core';
import {getApiBase} from '../api/client';

export interface AdminNote {
  id: string;
  title: string;
  content: string;
  userId: string | null;
  isPublic: string;
  createdAt: string;
  updatedAt: string;
  user?: {
    firstName?: string;
    lastName?: string;
    email?: string;
  };
}

function formatDate(dateString: string | null): string {
  if (!dateString) return 'N/A';
  try {
    const date = new Date(dateString);
    if (isNaN(date.getTime())) return 'Invalid Date';
    return date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  } catch {
    return 'Invalid Date';
  }
}

function getUserDisplayName(note: AdminNote): string {
  if (note.user) {
    if (note.user.firstName) {
      const name = `${note.user.firstName} ${note.user.lastName || ''}`.trim();
      return name;
    }
    if (note.user.email) return note.user.email;
  }
  if (note.userId) return `User #${note.userId}`;
  return 'Anonymous';
}

interface AdminNotesTableProps {
  notes: AdminNote[];
  loading: boolean;
  error: string | null;
  adminApiKey: string | null;
  onRefetch: () => void;
  onCreateClick?: () => void;
  showCreateButton?: boolean;
  'data-testid'?: string;
}

export function AdminNotesTable({
  notes,
  loading,
  error,
  adminApiKey,
  onRefetch,
  'data-testid': dataTestId,
}: AdminNotesTableProps) {
  const [deleteError, setDeleteError] = useState<string | null>(null);
  const [regexInput, setRegexInput] = useState('');
  const [deleteByRegexLoading, setDeleteByRegexLoading] = useState(false);

  const handleDeleteByRegex = async () => {
    if (!adminApiKey || !regexInput.trim()) return;
    try {
      setDeleteError(null);
      setDeleteByRegexLoading(true);
      const base = getApiBase();
      const url = base ? `${base}/api/notes/admin/delete-by-regex` : '/api/notes/admin/delete-by-regex';
      const res = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-API-Key': adminApiKey,
        },
        body: JSON.stringify({contentRegex: regexInput.trim()}),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error((err as {error?: string}).error || `Failed: ${res.status}`);
      }
      await res.json();
      setRegexInput('');
      onRefetch();
    } catch (err) {
      setDeleteError(err instanceof Error ? err.message : 'Failed to delete by regex');
    } finally {
      setDeleteByRegexLoading(false);
    }
  };

  const handleAdminDelete = async (noteId: string) => {
    if (!adminApiKey) return;
    if (!window.confirm('Are you sure you want to delete this note?')) return;
    try {
      setDeleteError(null);
      const base = getApiBase();
      const url = base ? `${base}/api/notes/${noteId}/admin` : `/api/notes/${noteId}/admin`;
      const response = await fetch(url, {
        method: 'DELETE',
        headers: {'X-API-Key': adminApiKey},
      });
      if (!response.ok) throw new Error(`Failed to delete note: ${response.status}`);
      onRefetch();
    } catch (err) {
      console.error('Error deleting note as admin:', err);
      setDeleteError(err instanceof Error ? err.message : 'Failed to delete note');
    }
  };

  return (
    <Paper
      style={{padding: '1.5rem', borderColor: '#e5e7eb'}}
      withBorder
      shadow='sm'
      data-testid={dataTestId ?? 'admin-notes-table'}
    >
      {/* Section header - always visible */}
      <div style={{marginBottom: '1.5rem'}}>
        <Text size='xl' fw={700} c='dark'>
          All Notes (Admin View)
        </Text>
        <Text size='sm' c='dimmed'>
          View and manage all notes in the system
        </Text>
      </div>

      {/* Delete notes matching regex */}
      <Group align='flex-end' gap='xs' mb='md'>
        <TextInput
          placeholder='e.g. e2e- or ^test'
          label='Delete notes matching regex (content/title)'
          value={regexInput}
          onChange={(e) => setRegexInput(e.currentTarget.value)}
          style={{flex: 1, minWidth: 200}}
        />
        <Button
          variant='light'
          color='red'
          onClick={handleDeleteByRegex}
          loading={deleteByRegexLoading}
          disabled={!regexInput.trim() || !adminApiKey}
        >
          Delete matching notes
        </Button>
      </Group>

      {(error || deleteError) && (
        <Alert color='red' mb='md'>
          {error || deleteError}
        </Alert>
      )}

      {loading ? (
        <Text c='dimmed' ta='center' py='xl'>
          Loading notes...
        </Text>
      ) : notes.length === 0 ? (
        <Text c='dimmed' ta='center' py='xl' fs='italic'>
          No notes found in the system
        </Text>
      ) : (
        <div style={{overflowX: 'auto', borderRadius: '0.5rem', border: '1px solid #e5e7eb'}}>
          <table
            style={{
              width: '100%',
              borderCollapse: 'collapse',
              fontSize: '0.875rem',
            }}
          >
            <thead style={{background: '#f3f4f6'}}>
              <tr>
                {['Title', 'Content Preview', 'Status', 'Author', 'Created', 'Actions'].map((h) => (
                  <th
                    key={h}
                    style={{
                      textAlign: 'left',
                      padding: '0.75rem 1rem',
                      fontWeight: 600,
                      color: '#374151',
                      fontSize: '0.75rem',
                      textTransform: 'uppercase',
                      letterSpacing: '0.05em',
                    }}
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {notes.map((note) => (
                <tr
                  key={note.id}
                  style={{borderTop: '1px solid #e5e7eb'}}
                  onMouseOver={(e) => {
                    (e.currentTarget as HTMLTableRowElement).style.background = '#f9fafb';
                  }}
                  onMouseOut={(e) => {
                    (e.currentTarget as HTMLTableRowElement).style.background = '';
                  }}
                >
                  <td style={{padding: '0.75rem 1rem', color: '#374151'}}>{note.title || 'Untitled'}</td>
                  <td
                    style={{
                      padding: '0.75rem 1rem',
                      color: '#374151',
                      maxWidth: 300,
                      overflow: 'hidden',
                      textOverflow: 'ellipsis',
                      whiteSpace: 'nowrap',
                    }}
                  >
                    {note.content
                      ? note.content.length > 60
                        ? `${note.content.substring(0, 60)}…`
                        : note.content
                      : '(No content)'}
                  </td>
                  <td style={{padding: '0.75rem 1rem'}}>
                    <span
                      style={{
                        display: 'inline-block',
                        fontSize: '0.75rem',
                        fontWeight: 500,
                        padding: '0.125rem 0.5rem',
                        borderRadius: 999,
                        background: note.isPublic === 'true' ? '#dcfce7' : '#ede9fe',
                        color: note.isPublic === 'true' ? '#15803d' : '#7c3aed',
                      }}
                    >
                      {note.isPublic === 'true' ? 'Public' : 'Private'}
                    </span>
                  </td>
                  <td style={{padding: '0.75rem 1rem', color: '#374151'}}>{getUserDisplayName(note)}</td>
                  <td style={{padding: '0.75rem 1rem', color: '#374151'}}>{formatDate(note.createdAt)}</td>
                  <td style={{padding: '0.75rem 1rem'}}>
                    <div style={{display: 'flex', gap: '0.75rem'}}>
                      <button
                        type='button'
                        onClick={() => handleAdminDelete(note.id)}
                        style={{
                          background: 'none',
                          border: 'none',
                          cursor: 'pointer',
                          fontSize: 14,
                          fontWeight: 500,
                          color: '#dc2626',
                          padding: 0,
                        }}
                        onMouseOver={(e) => {
                          e.currentTarget.style.color = '#b91c1c';
                        }}
                        onMouseOut={(e) => {
                          e.currentTarget.style.color = '#dc2626';
                        }}
                      >
                        Delete
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </Paper>
  );
}
