// svelte/src/lib/components/GlobalSearch.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { base } from '$app/paths';
	import { searchStore } from '$lib/stores/searchStore';

	interface Props {
		adminApiKey?: string | null;
	}
	let { adminApiKey = null }: Props = $props();

	let query = $state('');
	let results = $state<import('$lib/stores/searchStore').SearchNote[]>([]);
	let loading = $state(false);
	let open = $state(false);
	let containerEl: HTMLDivElement;
	let debounceId: ReturnType<typeof setTimeout> | null = null;

	$effect(() => {
		const q = query.trim();
		if (!q) {
			results = [];
			open = false;
			searchStore.clearSearch();
			return;
		}
		if (debounceId) clearTimeout(debounceId);
		debounceId = setTimeout(async () => {
			loading = true;
			try {
				const headers: Record<string, string> = {};
				if (typeof window !== 'undefined' && (window as any).Clerk?.session) {
					const token = await (window as any).Clerk.session.getToken();
					if (token) headers['Authorization'] = `Bearer ${token}`;
				}
				if (adminApiKey) headers['X-API-Key'] = adminApiKey;
				// API is at origin root; do not use SPA base (e.g. /svelte) or request returns HTML
				const res = await fetch(`/api/notes/search?q=${encodeURIComponent(q)}`, { headers });
				if (!res.ok) throw new Error('Search failed');
				const data = await res.json();
				const list = Array.isArray(data) ? data : [];
				results = list;
				searchStore.setSearch(q, list);
				open = true;
			} catch {
				results = [];
				searchStore.setSearch(q, []);
			} finally {
				loading = false;
			}
		}, 200);
		return () => {
			if (debounceId) clearTimeout(debounceId);
		};
	});

	function handleClickOutside(e: MouseEvent) {
		if (containerEl && !containerEl.contains(e.target as Node)) open = false;
	}

	function clearAndGo() {
		open = false;
		query = '';
		searchStore.clearSearch();
	}
</script>

<svelte:window on:mousedown={handleClickOutside} />

<div bind:this={containerEl} class="global-search">
	<input
		type="search"
		placeholder="Search notes…"
		bind:value={query}
		onfocus={() => query.trim() && (open = true)}
		class="search-input"
		aria-label="Search notes"
		data-testid="global-search-input"
	/>
	{#if open}
		<div class="search-dropdown">
			{#if loading}
				<div class="search-item search-muted">Searching…</div>
			{:else if results.length === 0}
				<div class="search-item search-muted">No notes found</div>
			{:else}
				{#each results as note (note.id)}
					<button
						type="button"
						class="search-item search-result"
						onclick={() => { clearAndGo(); goto(`${base}/notes/${note.id}/edit`); }}
					>
						<span class="search-result-title">{note.title || 'Untitled'}</span>
						{#if note.content}
							<span class="search-result-snippet">{note.content.slice(0, 60)}…</span>
						{/if}
					</button>
				{/each}
			{/if}
		</div>
	{/if}
</div>

<style>
	.global-search {
		position: relative;
		flex: 1;
		max-width: 320px;
		margin: 0 1rem;
	}
	.search-input {
		width: 100%;
		padding: 0.375rem 0.75rem;
		font-size: 0.875rem;
		border: 1px solid #e5e7eb;
		border-radius: 0.25rem;
		outline: none;
	}
	.search-dropdown {
		position: absolute;
		top: 100%;
		left: 0;
		right: 0;
		margin-top: 4px;
		background: #fff;
		border: 1px solid #e5e7eb;
		border-radius: 0.25rem;
		box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1);
		max-height: 320px;
		overflow: auto;
		z-index: 1001;
	}
	.search-item {
		display: block;
		width: 100%;
		padding: 0.5rem 0.75rem;
		font-size: 0.875rem;
		text-align: left;
		border: none;
		background: transparent;
		cursor: pointer;
	}
	.search-muted {
		color: #6b7280;
	}
	.search-result:hover {
		background: #f9fafb;
	}
	.search-result-title {
		font-weight: 600;
		color: #111827;
	}
	.search-result-snippet {
		display: block;
		color: #6b7280;
		margin-top: 2px;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}
</style>

// react/src/components/GlobalSearch.tsx
import { useState, useRef, useEffect } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "@clerk/clerk-react";
import { useNoteContext, type SearchNote } from "../context/NoteContext";

// API is always at origin root; do not use SPA base (e.g. /react) or request hits SPA and returns HTML
const SEARCH_URL = "/api/notes/search";

interface GlobalSearchProps {
  adminApiKey?: string | null;
}

export function GlobalSearch({ adminApiKey = null }: GlobalSearchProps) {
  const { getToken } = useAuth();
  const { setSearch, clearSearch } = useNoteContext();
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<SearchNote[]>([]);
  const [loading, setLoading] = useState(false);
  const [open, setOpen] = useState(false);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!query.trim()) {
      setResults([]);
      setOpen(false);
      clearSearch();
      return;
    }
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(async () => {
      setLoading(true);
      try {
        const url = `${SEARCH_URL}?q=${encodeURIComponent(query.trim())}`;
        const headers: HeadersInit = {};
        const token = await getToken();
        if (token) headers.Authorization = `Bearer ${token}`;
        if (adminApiKey) (headers as Record<string, string>)["X-API-Key"] = adminApiKey;
        const res = await fetch(url, { headers });
        if (!res.ok) throw new Error("Search failed");
        const data = await res.json();
        const list = Array.isArray(data) ? data : [];
        setResults(list);
        setSearch(query.trim(), list);
        setOpen(true);
      } catch {
        setResults([]);
        setSearch(query.trim(), []);
      } finally {
        setLoading(false);
      }
    }, 200);
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, [query, setSearch, clearSearch, getToken, adminApiKey]);

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  return (
    <div ref={containerRef} style={{ position: "relative", flex: "1", maxWidth: 320, margin: "0 1rem" }}>
      <input
        type="search"
        placeholder="Search notes…"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        onFocus={() => query.trim() && setOpen(true)}
        data-testid="global-search-input"
        style={{
          width: "100%",
          padding: "0.375rem 0.75rem",
          fontSize: "0.875rem",
          border: "1px solid #e5e7eb",
          borderRadius: "0.25rem",
          outline: "none",
        }}
        aria-label="Search notes"
      />
      {open && (
        <div
          style={{
            position: "absolute",
            top: "100%",
            left: 0,
            right: 0,
            marginTop: 4,
            background: "#fff",
            border: "1px solid #e5e7eb",
            borderRadius: "0.25rem",
            boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)",
            maxHeight: 320,
            overflow: "auto",
            zIndex: 1001,
          }}
        >
          {loading ? (
            <div style={{ padding: "0.75rem", color: "#6b7280", fontSize: "0.875rem" }}>Searching…</div>
          ) : results.length === 0 ? (
            <div style={{ padding: "0.75rem", color: "#6b7280", fontSize: "0.875rem" }}>No notes found</div>
          ) : (
            results.map((note) => (
              <Link
                key={note.id}
                to={`/notes/${note.id}/edit`}
                onClick={() => { setOpen(false); setQuery(""); clearSearch(); }}
                style={{
                  display: "block",
                  padding: "0.5rem 0.75rem",
                  fontSize: "0.875rem",
                  color: "#111827",
                  textDecoration: "none",
                  borderBottom: "1px solid #f3f4f6",
                }}
                onMouseOver={(e) => {
                  (e.currentTarget as HTMLElement).style.background = "#f9fafb";
                }}
                onMouseOut={(e) => {
                  (e.currentTarget as HTMLElement).style.background = "transparent";
                }}
              >
                <span style={{ fontWeight: 600 }}>{note.title || "Untitled"}</span>
                {note.content && (
                  <span style={{ display: "block", color: "#6b7280", marginTop: 2, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                    {note.content.slice(0, 60)}…
                  </span>
                )}
              </Link>
            ))
          )}
        </div>
      )}
    </div>
  );
}
