// angular/src/app/components/storybook-frame/storybook-frame.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-storybook-frame',
  standalone: true,
  template: `
    <main class="storybook-page">
      <h1 class="storybook-title">Angular Storybook (Chromatic)</h1>

      @if (!storybookUrl) {
        <p class="storybook-hint">
          Storybook URL is not configured. Set
          <code>window.ANGULAR_STORYBOOK_URL</code> in a global script to the Chromatic-hosted
          Angular Storybook URL.
        </p>
      } @else {
        <div class="storybook-frame-wrapper">
          <iframe [src]="storybookUrl" title="Angular Storybook" class="storybook-iframe"></iframe>
        </div>
      }
    </main>
  `,
  styles: [
    `
      .storybook-page {
        padding: 1.5rem;
        display: flex;
        flex-direction: column;
        gap: 1rem;
        height: 100vh;
        box-sizing: border-box;
      }

      .storybook-title {
        font-size: 1.5rem;
        font-weight: 600;
      }

      .storybook-hint {
        color: #6b7280;
      }

      .storybook-frame-wrapper {
        flex: 1;
        min-height: 0;
      }

      .storybook-iframe {
        width: 100%;
        height: 100%;
        border: 1px solid #e5e7eb;
        border-radius: 0.5rem;
        background: #fff;
      }
    `,
  ],
})
export class StorybookFrameComponent {
  storybookUrl: string | null;

  constructor() {
    if (typeof window !== 'undefined' && (window as any).ANGULAR_STORYBOOK_URL) {
      this.storybookUrl = (window as any).ANGULAR_STORYBOOK_URL as string;
    } else {
      this.storybookUrl = null;
    }
  }
}

// react/src/components/StorybookFrame.tsx
import React from 'react';

const STORYBOOK_URL = import.meta.env.VITE_STORYBOOK_REACT_URL as string | undefined;

export const StorybookFrame: React.FC = () => {
  if (!STORYBOOK_URL) {
    return (
      <div style={{padding: '1.5rem'}}>
        <h1 style={{fontSize: '1.5rem', marginBottom: '0.5rem'}}>React Storybook (Chromatic)</h1>
        <p style={{color: '#6b7280'}}>
          Storybook URL is not configured. Set <code>VITE_STORYBOOK_REACT_URL</code> in
          <code>react/.env</code> to the Chromatic-hosted Storybook URL.
        </p>
      </div>
    );
  }

  return (
    <div style={{display: 'flex', flexDirection: 'column', height: '100%', padding: '1rem'}}>
      <h1 style={{fontSize: '1.5rem', marginBottom: '0.75rem'}}>React Storybook (Chromatic)</h1>
      <div style={{flex: 1, minHeight: 0}}>
        <iframe
          src={STORYBOOK_URL}
          title='React Storybook'
          style={{
            width: '100%',
            height: '100%',
            border: '1px solid #e5e7eb',
            borderRadius: '0.5rem',
            backgroundColor: 'white',
          }}
        />
      </div>
    </div>
  );
};
